name: music_remover
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  http: ^1.6.0
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Music_Remover.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
